import JSZip from 'jszip';
import { saveAs } from 'file-saver';
import { Node, Edge } from '@xyflow/react';
import { NodeData, TrainingConfig, DatasetConfig, ProjectMetadata } from '../../types/network';
import { generateFunctionalCode, generateSequentialCode, generatePyTorchCode, generateJSCode, generateTrainingScript } from '../TensorFlow/codeGen';

export const downloadTextFile = (content: string, filename: string) => {
  const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
  saveAs(blob, filename);
};

export const exportProjectJsonFile = (
  metadata: ProjectMetadata,
  tabs: any[],
  activeTabId: string,
  trainingConfig: TrainingConfig,
  datasetConfig: DatasetConfig
) => {
  const projectData = {
    metadata,
    tabs,
    activeTabId,
    trainingConfig,
    datasetConfig,
    version: '1.0.0'
  };

  const jsonStr = JSON.stringify(projectData, null, 2);
  const blob = new Blob([jsonStr], { type: 'application/json;charset=utf-8' });
  saveAs(blob, `${metadata.name.replace(/\s+/g, '_')}_project.json`);
};

export const exportProjectZipFile = async (
  metadata: ProjectMetadata,
  nodes: Node<NodeData>[],
  edges: Edge[],
  trainingConfig: TrainingConfig,
  datasetConfig: DatasetConfig,
  allTabs: any[]
) => {
  const zip = new JSZip();

  // 1. Generate model.py (Pure model definition)
  const functionalCode = generateFunctionalCode(nodes, edges);
  const sequentialCode = generateSequentialCode(nodes, edges);
  
  const modelFileContent = 
    `# -*- coding: utf-8 -*-\n` +
    `\"\"\"\n` +
    `Model definition file for ${metadata.name}\n` +
    `Generated by Keras Flow Designer\n` +
    `\"\"\"\n` +
    `import tensorflow as tf\n` +
    `from tensorflow import keras\n` +
    `from tensorflow.keras import layers, regularizers, constraints\n\n` +
    `# --- Keras Functional API ---\n` +
    `def create_model():\n` +
    `${functionalCode.split('\n').map(line => '    ' + line).join('\n')}\n` +
    `    return model\n\n` +
    `# --- Keras Sequential API (if possible) ---\n` +
    `# def create_sequential_model():\n` +
    `${sequentialCode.split('\n').map(line => '#   ' + line).join('\n')}\n`;

  zip.file('model.py', modelFileContent);

  // 2. Generate training script train.py
  const trainingScript = generateTrainingScript(nodes, edges, trainingConfig, datasetConfig);
  zip.file('train.py', trainingScript);

  // 3. Generate requirements.txt
  const requirementsContent = 
    `tensorflow>=2.16.0\n` +
    `numpy>=1.23.0\n` +
    `pandas>=2.0.0\n` +
    `scikit-learn>=1.2.0\n`;
  zip.file('requirements.txt', requirementsContent);

  // 4. Generate config.json (Visual project file for re-importing)
  const projectData = {
    metadata,
    tabs: allTabs,
    activeTabId: metadata.id,
    trainingConfig,
    datasetConfig,
    version: '1.0.0'
  };
  zip.file('config.json', JSON.stringify(projectData, null, 2));

  // 5. Generate README.md
  const readmeContent = 
    `# ${metadata.name}\n\n` +
    `${metadata.description || 'Visual Keras Neural Network project.'}\n\n` +
    `This repository contains the training script, model structure, and requirements generated using Keras Flow Designer.\n\n` +
    `## Files Included\n\n` +
    `- \`model.py\`: Contains the Keras Functional & Sequential API model structure.\n` +
    `- \`train.py\`: A complete pipeline training script that handles dataset loading, compile, callbacks, and model training.\n` +
    `- \`requirements.txt\`: Python dependencies needed to execute the training.\n` +
    `- \`config.json\`: Saved project file. Re-import this file in Keras Flow Designer to modify the graph.\n\n` +
    `## How to Run\n\n` +
    `1. Ensure you have Python installed.\n` +
    `2. Create a virtual environment and install dependencies:\n` +
    `   \`\`\`bash\n` +
    `   python -m venv venv\n` +
    `   source venv/bin/activate  # On Windows: venv\\Scripts\\activate\n` +
    `   pip install -r requirements.txt\n` +
    `   \`\`\`\n` +
    `3. Start training:\n` +
    `   \`\`\`bash\n` +
    `   python train.py\n` +
    `   \`\`\`\n`;
  zip.file('README.md', readmeContent);

  // Generate zip file and download
  const content = await zip.generateAsync({ type: 'blob' });
  saveAs(content, `${metadata.name.replace(/\s+/g, '_')}_workspace.zip`);
};
